In [9]:
!pip install sentence-transformers
!pip install faiss-cpu
!pip install rank-bm25
!pip install pandas numpy

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.2.2)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.4.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.9.0+cpu)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.20.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.21.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (1.13.2)
Requirement already satisfied: numpy<3.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.0)
Collecting rank-bm25
  Downloading rank_bm25-0.2.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rank-bm25) (2.0.2)
Downloading rank_bm25-0.2.2-py3-none-any.whl (8.6 kB)
Installing collected packages: rank-bm25
Successfully installed rank-bm25-0.2.2
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [11]:
import pandas as pd
import numpy as np
import faiss
from sentence_transformers import SentenceTransformer
from rank_bm25 import BM25Okapi

In [13]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2026.1.4)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.4.4)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.5.1)

In [14]:
from google.colab import files
files.upload()

Saving HM_Fashion_Dataset_2000.xlsx to HM_Fashion_Dataset_2000.xlsx

{'HM_Fashion_Dataset_2000.xlsx': b'PK\x03\x04\x14\x00\x00\x00\x08\x00PHO\\F\xc7MH\x95\x00\x00\x00\xcd\x00\x00\x00\x10\x00\x00\x00docProps/app.xmlM\xcfM\x0b\xc20\x0c\x06\xe0\xbfRv\xb7\x99\x8a\x1e\xa4\x0eD=\x8a\x9e\xbc\xcf.u\x85\xb6)m\x84\xfa\xef\xed\x04?nyy\xc8\x1b\xa2.\x89"&\xb6\x98E\xf1.\xe4m32\xc7\r@\xd6#\xfa>\xcb\xca\xa1\x8a\xa1\xe4{\xae1\xdd\x81\x8c\xb1\x1a\x0f\xa4\x1f\x1e\x03\xc3\xa2m\xd7\x80\x851\x0c8\xcc\xe2\xb7\xb0\xe9\xd4.Fgu\xcf\x96Bw\xb2:Q&\xc3\xe2X4:\xb1\'\x1f\xab\xdc\x1c\n\x10\xe7z%>\x8b\x13K9\x97+\x05\xff\x8bS\xcb\x15S\x9e\xe6\xcao\xfcd\x05\xbf\x07\xba\x17PK\x03\x04\x14\x00\x00\x00\x08\x00PHO\\c|\x02\xc6\xee\x00\x00\x00+\x02\x00\x00\x11\x00\x00\x00docProps/core.xml\xcd\x92\xc1j\xc30\x0c\x86_e\xf8\x9e\xc8IXa&\xcd\xa5\xa3\xa7\x0e\x06+l\xecfl\xb55\x8bcck$}\xfb9^\x9b2\xb6\x07\xd8\xd1\xd2\xefO\x9f@\xad\xf2B\xb9\x80\xcf\xc1y\x0cd0\xdeM\xb6\x1f\xa2P~\xcdND^\x00DuB+c\x99\x12Cj\x1e\\\xb0\x92\xd23\x1c\xc1K\xf5!\x8f\x085\xe7+\xb0HRK\x920\x03\x0b\xbf\x10Y\xd7j%T@I.\\\xf0Z-x\xff\x19\xfa\x0c\xd3\n\xb0G\x8b\x03E\xa8\xca\nX7O\xf4\xe7\xa9o\xe1\x06\x98a\x84\xc1\xc6\xef\x02\xea\x85\x98\xab\x7fbs\x07\xd8%9E\xb3\xa4\xc6q,\xc7&\xe7\xd2\x0e\x15\xbc=\xed^\xf2\xba\x85\x19"\xc9Aa\xfa\x15\x8d\xa0\xb3\xc75\xbbN~m6\x8f\xfb-\xebj^\xaf\n^\x17\xd5\xfd\x9e?\x08^\x8b\xa6y\x9f]\x7f\xf8\xdd\x84\xad\xd3\xe6`\xfe\xb1\xf1U\xb0k\xe1\xd7]t_PK\x03\x04\x14\x00\x00\x00\x08\x00PHO\\\x99\\\x9c#\x10\x06\x00\x00\x9c\'\x00\x00\x13\x00\x00\x00xl/theme/theme1.xml\xedZ[s\xda8\x14~\xef\xaf\xd0xg\xf6m\x0b\xc66\x81\xb6\xb4\x13siv\xdb\xb4\x99\x84\xedN\x1f\x85\x11X\x8dlyd\x91\x84\x7f\xbfG6\x10\xcb\x96\r\xed\x92M\xba\x9b<\x04,\xe9\xfb\xceEG\xe7\xe88y\xf3\xee.b\xe8\x86\x88\x94\xf2x`\xd9/\xdb\xd6\xbb\xb7/\xde\xe0W2$\x11A0\x19\xa7\xaf\xf0\xc0\n\xa5L^\xb5Zi\x00\xc38}\xc9\x13\x12\xc3\xdc\x82\x8b\x08Kx\x14\xcb\xd6\\\xe0[\x1a/#\xd6\xea\xb4\xdb\xddV\x84il\xa1\x18Gd`}^,h@\xd0TQZo_ \xb4\xe5\x1f3\xf8\x15\xcbT\x8de\xa3\x01\x13WA&\xb9\x88\xb4\xf2\xf9l\xc5\xfc\xda\xde>e\xcf\xe9:\x1d2\x81n0\x1bX \x7f\xceo\xa7\xe4NZ\x88\xe1T\xc2\xc4\xc0jg?Vk\xc7\xd1\xd2H\x80\x82\xc9}\x94\x05\xbaI\xf6\xa3\xd3\x15\x082\r;:\x9dX\xcev|\xf6\xc4\xed\x9f\x8c\xca\xdat4m\x1a\xe0\xe3\xf1x8\xb6\xcb\xd2\x8bp\x1c\x04\xe0Q\xbb\x9e\xc2\x9d\xf4l\xbf\xa4A\t\xb4\xa3i\xd0d\xd8\xf6\xda\xae\x91\xa6\xaa\x8dSO\xd3\xf7}\xdf\xeb\x9bh\x9c\n\x8d[O\xd3kw\xdd\xd3\x8e\x89\xc6\xad\xd0x\r\xbe\xf1O\x87\xc3\xae\x89\xc6\xab\xd0t\xebi&\'\xfd\xaek\xa4\xe9\x16hBF\xe3\xebz\x12\x15\xb5\xe5@\xd3 \x00Xpv\xd6\xcc\xd2\x03\x96^)\xfau\x94\x1a\xd9\x1d\xbb\xddA\\\xf0X\xee9\x89\x11\xfe\xc6\xc5\x04\xd6i\xd2\x19\x964Fr\x9d\x90\x05\x0e\x007\xc4\xd1LP|\xafA\xb6\x8a\xe0\xc2\x92\xd2\\\x90\xd6\xcf)\xb5P\x1a\x08\x9a\xc8\x81\xf5G\x82!\xc5\xdc\xaf\xfd\xf5\x97\xbb\xc9\xa43z\x9d}:\xcek\x94\x7fi\xab\x01\xa7\xed\xbb\x9b\xcf\x93\xfcs\xe8\xe4\x9f\xa7\x93\xd7MB\xcep\xbc,\t\xf1\xfb#[a\x87\'n;\x13r:\x1cgB|\xcf\xf6\xf6\x91\xa5%2\xcf\xef\xf9\n\xebN<g\x1fV\x96\xb0]\xcf\xcf\xe4\x9e\x8cr#\xbb\xdd\xf6X}\xf6OGn#\xd7\xa9\xc0\xb3"\xd7\x94F$E\x9f\xc8-\xba\xe4\x118\xb5I\r2\x13?\x08\x9d\x86\x98jP\x1c\x02\xa4\t1\x96\xa1\x86\xf8\xb4\xc6\xac\x11\xe0\x13}\xb7\xbe\x08\xc8\xdf\x8d\x88\xf7\xabo\x9a=W\xa1XI\xda\x84\xf8\x10F\x1a\xe2\x9cs\xe6s\xd1l\xfb\x07\xa5F\xd1\xf6U\xbc\xdc\xa3\x97X\x15\x01\x97\x18\xdf4\xaa5,\xc5\xd6x\x95\xc0\xf1\xad\x9c<\x1d\x13\x12\xcd\x94\x0b\x06A\x86\x97$&\x12\xa99~MH\x13\xfe+\xa5\xda\xfe\x9c\xd3@\xf0\x94/$\xfaJ\x91\x8fi\xb3#\xa7t&\xcd\xe83\x1a\xc1F\xaf\x1bu\x87h\xd2<z\xfe\x05\xf9\x9c5\n\x1c\x91\x1b\x1d\x02g\x1b\xb3F!\x84i\xbb\xf0\x1e\xaf$\x8e\x9a\xad\xc2\x11+B>b\x196\x1ar\xb5\x16\x81\xb6q\xa9\x84`Z\x12\xc6\xd1xN\xd2\xb4\x11\xfcY\xac5\x93>`\xc8\xec\xcd\x91u\xce\xd6\x91\x0e\x11\x92^7B>b\xce\x8b\x90\x11\xbf\x1e\x868J\x9a\xed\xa2qX\x04\xfd\x9e^\xc3I\xc1\xe8\x82\xcbf\xfd\xb8~\x86\xd53l,\x8e\xf7G\xd4\x17J\xe4\x0f&\xa7?\xe924\x07\xa3\x9aY\t\xbd\x84Vj\x9f\xaa\x874>\xa8\x1e2\n\x05\xf1\xb9\x1e>\xe5zx\n7\x96\xc6\xbcP\xae\x82{\x01\xff\xd1\xda7\xc2\xab\xf8\x82\xc09\x7f.}\xcf\xa5\xef\xb9\xf4=\xa1\xd2\xb77#}g\xc1\xd3\x8b[\xdeFn[\xc4\xfb\xae1\xda\xd74.(cWr\xcd\xc8\xc7T\xaf\x93)\xd89\x9f\xc0\xec\xfdh>\x9e\xf1\xed\xfa\xd9$\x84\xaf\x9aY-#\x16\x90K\x81\xb3A$\xb8\xfc\x8b\xca\xf0*\xc4\t\xe8d[%\t\xcbT\xd3e7\x8a\x12\x9eB\x1bn\xe9S\xf5J\x95\xd7\xe5\xaf\xb9(\xb8<[\xe4\xe9\xaf\xa1t>,\xcf\xf9<_\xe7\xb4\xcd\x0b3C\xb7rK\xea\xb6\x94\xbe\xb5&8J\xf4\xb1\xccpN\x1e\xcb\x0c;g<\x92\x1d\xb6w\xa0\x1d5\xfb\xf6]v\xe4#\xa50S\x97C\xb8\x1aB\xbe\x03m\xba\x9d\xdc:8\x9e\x98\x91\xb9\n\xd3R\x90o\xc3\xf9\xe9\xc5x\x1a\xe29\xd9\x04\xb9}\x98Wm\xe7\xd8\xd1\xd1\xfb\xe7\xc1Q\xb0\xa3\xef<\x96\x1d\xc7\x88\xf2\xa2!\xee\xa1\x86\x98\xcf\xc3C\x87y{_\x98g\x95\xc6P4\x14ml\xac$,F\xb7`\xb8\xd7\xf1,\x14\xe0d`-\xa0\x07\x83\xafQ\x02\xf2RU`1[\xc6\x03+\x90\xa2|L\x8cE\xe8p\xe7\x97\\_\xe3\xd1\x92\xe3\xdb\xa6e\xb5n\xaf)w\x19m"R9\xc2i\x98\x13g\xab\xca\xdee\xb1\xc1U\x1d\xcfU[\xf2\xb0\xbej=\xb4\x15N\xcf\xfeY\xad\xc8\x9f\x0c\x11N\x16\x0b\x12Hc\x94\x17\xa6J\xa2\xf3\x19S\xbe\xe7+I\xc4U8\xbfE3\xb6\x12\x97\x18\xbc\xe3\xe6\xc7qNS\xb8\x12v\xb6\x0f\x022\xb9\xbb9\xa9ze1g\xa6\xf2\xdf-\x0c\t,[\x88Y\x12\xe2M]\xed\xd5\xe7\x9b\x9c\xaez"v\xfa\x97w\xc1`\xf2\xfdp\xc9G\x0f\xe5;\xe7_\xf4]C\xae~\xf6\xdd\xe3\xfan\x93;HL\x9cy\xc5\x11\x01tE\x02#\x95\x1c\x06\x16\x172\xe4P\xee\x92\x90\x06\x13\x01\xcd\x94\xc9D\xf0\x02\x82d\xa6\x1c\x80\x98\xfa\x0b\xbd\xf2\x0c\xb9)\x15\xce\xad>9\x7fE,\x83\x86N^\xd2%\x12\x14\x8a\xb0\x0c\x05!\x17r\xe3\xef\xef\x93jw\x8c\xd7\xfa,\x81m\x84T2d\xd5\x17\xcaC\x89\xc1=3rC\xd8T%\xf3\xae\xda&\x0b\x85\xdb\xe2T\xcd\xbb\x1a\xbe&`K\xc3zn\x9d-\'\xff\xdb^\xd4=\xb4\x17=F\xf3\xa3\x99\xe0\x1e\xb3\x87s\x9bz\xb8\xc2E\xac\xffX\xd6\x1e\xf92\xdf9p\xdb:\xde\x03^\xe6\x13,C\xa4~\xc1}\x8a\x8a\x80\x11\xabb\xbe\xba\xafO\xf9%\x9c;\xb4{\xf1\x81 \x9b\xfc\xd6\xdb\xa4\xf6\xdd\xe0\x0c|\xd4\xabZ\xa5d+\x11?K\x07|\x1f\x92\x06c\x8c[\xf44_\x8f\x14b\xad\xa6\xb1\xad\xc6\xda1\x0cy\x80X\xf3\x0c\xa1f8\xdf\x87E\x9a\x1a3\xd5\x8b\xac9\x8d\noA\xd5@\xe5?\xdb\xd4\rh\xf6\r4\x1c\x91\x05^1\x99\xb66\xa3\xe4N\n<\xdc\xfe\xef\r\xb0\xc2\xc4\x8e\xe1\xed\x8b\xbf\x01PK\x03\x04\x14\x00\x00\x00\x08\x00PHO\\\xe5Cd\xc4\xfe\xc6\x01\x006\xf5\x10\x00\x18\x00\x00\x00xl/worksheets/sheet1.xml\xbc\xbdm\xcf,\xc7q\xa6\xf9W\x08\xfd\x80RU\xd6Kf\x0ed\x01S\xe2\xf8iq`@\xb0<k\xec\'\x83&\x8f\xa5\x03\xf1m\x0f\x0f\xc7\xab\xf9\xf5\xdb]\xd5\xfdtFE\\\xd1\x95tb\xfda\xd7\xe3\xe6\x1d\xddO0\x98\x19qed\xe4\xef\xfe\xf3\xc7O\x7f\xfb\xf9\xaf\x1f>|\xfe\xe2\xff\xfd\xfe\xbb\x1f~\xfe\x87\xdf\xfc\xf5\xf3\xe7\x9f\xfe\xdbo\x7f\xfb\xf37\x7f\xfd\xf0\xfd\xd7?w?\xfe\xf4\xe1\x87\xeb\'\xff\xf1\xe3\xa7\xef\xbf\xfe|\xfd\x7f~\xfa\xcbo\x7f\xfe\xe9\xd3\x87\xaf\xbf\xddD\xdf\x7f\xf7\xdb\xd0\xf7\xcbo\xbf\xff\xfa\xe3\x0f\xbf\xf9\xfd\xef\xb6\xff\xdb\x9f>\xfd\xfew?\xfe\xf2\xf9\xbb\x8f?|\xf8\xd3\xa7/~\xfe\xe5\xfb\xef\xbf\xfe\xf4\xf7\xf5\xc3w?\xfe\xe7?\xfcf\xf8\xcd\xe3\xff\xf0\xcf\x1f\xff\xf2\xd7\xcf\xb7\xff\xc3o\x7f\xff\xbb\x9f\xbe\xfe\xcb\x87?\x7f\xf8\xfc\xbf~\xfa\xd3\xa7\xeb\xff\xeb\xb7\xefV\xbe\xfd\xf8\xfd\x87\x1f~\xfe\xf8\xe3\x0f_|\xfa\xf0\x1f\xff\xf0\x9b\xff>\xfc\xb7\xaf\xae\xdf\xb6I\xb6\x7f\xe6\xff\xfa\xf8\xe1?\x7f.\xfe\xf7/n\x7f\xcc\xbf\xff\xf8\xe3\xdfn\xff\x8f?~\xfb\x0f\xbf\xe9o\xbf\xe9\xc3w\x1f\xbe\xf9|3\xf2\xf5\xf5\xff\xf7\xbf?\xfc\xe1\xc3w\xdf\xddl]\x7f\xc9\xffs7\xfb\x9b\xf7o\xbd\t\xcb\xff\xfda\xfd\x1f\xb7?\xff\xfa\xe7\xfc\xfb\xd7?\x7f\xf8\xc3\x8f\xdf\xfd\xeb\xc7o?\xff\xf5\x1f~\x93~\xf3\xc5\xb7\x1f\xfe\xe3\xeb_\xbe\xfb\xfc\xcf?\xfe\xe7\xe5\xc3\xfdO\x9a\xdf\x7f\xe0\x97_\x7f\xfe\xfa\xf7\xbf\xfb\xf4\xe3\x7f~\xf1\xe9\xf6\xa7\xfe\xfew\xdf\xdc\xfe\x97\xdbw_\xff\xb9\x8f?\xdc\\\xf4\xe7\xcf\x9f\xae\xff\xf7\x8f\xd7/\xfa\xfc\xfb\xaf?}\xfe\xf8\xcdw\x1f\xfe\xed\xe3\xb7\xbf\xfb\xed\xe7\xeb\xcf\xb8\xfd_\x7f\xfb\xcd]\xb5\x92\xea\xa7O?~\xfb\xcb7\x9f\xff\xed\x87\xaf\xbf\xff`\xe8\xfe\xf0J\xf7\xf9\xef?Y\xba/I\xf7\xcd\x8f\xdf\xfd\xf8\xc9\x10\xfc\x0f\x12\xfc\xbc\xfb\xdf\x90\xfc#\xff\xb6\x8f\xdfX?\xea\r\x7f\xd4/?\x7f\xfe\xf1\xfb\x0f\x9fl\xdf]\xf0{~\xf9\xf4\xcd_\xaf\xffJ\xff\xed\x9b\x1f\x7f\xf9\xe1\xb3\xa1\xfc#)?}\xfd\xf9\xe3\x0f\x7f1\x14_\x91\xe2\xdb\x0f?\x7f\xf3\xe9\xe3O\xda\x15\xbf\xbd\x06\xc8{\x94\x84\xf7(\t`\xe7\xbf\xff\xf3\xbf\xf4\xd7\xff\x19\xac\x18!\xcd\x16\xbf\xdf}\xf1\x7f_c\xff\xfa5\x7f\xfe\xdb\xc7O\xd6\x1f\xfb\x07\x92\x93\xe0K\x12\xec_d\x05\t)\xfe\xe7\xc7o\x7f\xb6"d\xff\xe7o\x8b\xcb\xff\xfe\xfd0\x85\xb9\xeb\xc3\xef~\xfb\xbf\xcb\x90 \x8b\x7f\xf8_\x7f\xfe\x974\x86l\xc5Ciu\x94\xf6\xfeX~6u\x93\xfc\xf4\xab\n\x0f\x7fq]4\xbf\xb8\xfd]\xd75\xef\xe3\xe7\xaf\xff\xfd\xbb\x0f\xdb\xff\xe5\x9b\xaf\x7f\xfe\xe5\xfaO~\xfd\xc3\xb7_\xfct\xfd/\xfe\xef_\xfc\xe7\x87\xaf?9\x111\xbeG\xc4\xe8GD\xb0"\x824\xff\xfa\xf1\x87\xcf\x1f>}\xf1\xf6\xe9\xc3\xdf\xbf\xf8\x97\x1f\x7f\xb2\xa2\x81\xa4\xf6?\xfe%\xfd\xe3\xb7\xaf\xb0"\x01\x7f\xd9\xf5\xbfcs\xb1\x18\x8b\x7f1\xf3|\xfdW3\x1c"\x81,n\x910\xf7\x8b\x15\t\xa5\xd1a>\x84B\xf9\xe1\xd8\x1d\x02\xef\xab\x93\xae\xdd\xfe\xa5o\x7f\xd4\x7f-\x0e\xa6\xf78\x98\xfc8\x18\xad8 \xcd\xfd\xc7\xfe\xeb_?~\xfe\xf0\xc5W_\x7f\xf3\xb7\x0f\xe6\xca@rT|\x89_x\xfb&+\x1eH\xf0Ov4L\xe5\x7f\xa6\xf30v9\x1d\xc2\x81\x0c\xde\xc2!\xce\xc9r\xd3\xa5\xb4\xba\x1c\xa2A|cw\xf8\xf4\xab\n\x07o\xff\xfa\xff\xe9\xbf\x1a\x0f\xf3{<\xcc~<LV<\x90\xe6_>}\xfd\xed\xc7\xdb\x1eu\xfd)\xebw\xd7\x9f{\xfb\xff\xfe\x9f\x0f\xd6\x86\xff\x07\xb2\x81\x8a/\x1d\xc57\x7f\xb3\x82\x82\x04\xb8H\xcc\xe5\x7f\xcfK?t\xe3a\x05\x7f#\x93\xb7\xb0\x18\x07;,\x84\xd5\xc3\xb2\xf3\xc7Y\xac\x12\xc7\r\xa3\xd6\xd1\xad\x96\x8b\xe5=<\x16?<f+<Hs\x8f\xe6\xfb6\x07\x1b\x07\x89a\xe3\xa0\x7f\x9c\x93\x08R\xc0R\xb1\x94\xff\xe1\x86\xd8w\xc7\x8d\x83\xecm!\x11\xa2\xe5\xa1Ki4\xf4\x87\x90XDH\xe4CH\x9cvn\x9b\x85"\xbeGB\xf4#\xc1\xda W\xd2\xfc\x8f\xef>\xfc\xe5\xeb\x1f>\xef\xdb\x1co\x1c$\xe7\x8d\x83\x14\x94G\xd0?\x8fKD,\xff\xcd\xe5q\xee\xc2a\xdf\x7f#\x93\xb7x\xc8\xf3l%Z\x97(\x16\x9eC<D\x11\x0f\x87\x8c\xf3\xab\n\x17\xb7Z\x1d\xd2{L$?&\xa2\x15\x13\xa4\xb9\'\xc1^RIRX\x1b\xe8\x1f\xa7`\xa0\x7f\x1eV\x86T\xae\x0cy\x0e]>.\rdp\x0b\x85e6\xab\x8b\xd2\xeap\\\x1a\xca\x0f\x8f\x81p\xd2\xafm\x96\x85\xfc\x1e\x02\xd9\x0f\x81d\x85\x00i\xfe\xb0\xff\x8a=\xdd\xf9\xf3\xd7\x9f>\x98L\x82\xd4$\xf8\x92\x04\x98M\x92\x00\x02!\x97\x81\x10c\xe8n\x81/\x02\x01\xff\xe0k \x84\xdeN\x1b\xb2\xb7&\x88\xaf<\x04\xc2y\xef\xb6\x89\x85\xa1\x7f\xc2\xa9\xde\x8f\x06+\xe2W\x14\xfd\xf9\xf3\xdf\xbf\xfb\xf8\xf3_\xbfX?|\xfc\x8b\x13\x0f\xac\xa7\x80@\xc5\xf6M&\x9e"\x05\xa1\x87\xbb\xe0\xfe\x9f\xea\x90\xe6\xae?\x96\x18hs\xab1b6w\naw8\xe2\x07\xf9\xad*\x9d\xac\xf1t#\x001\x14\xe4\x92\xe0\xd6\x1e\x1c\xb7\xc5\xce\x08\x0e\x12\xfdi\xfb\xf6mUC$\x85bdR\xa8\xa0=\x03\x05\x18\x18C\xf9\xafhN}7\x8d\xc7\xc0 \x9b\xb7\xc0\x18\xf2`\xa6\x94\xc2\xae\x0e\x0c\xf1\xad*\x898\xed\xe5VQ\xf1$\x95\x83\x8f*\x07\x13U\xa2\xe8\x9e\x05\xff\xf3\x87o\xbf\xf8\xf3\xf57|\xb6kO\x94\xb3\xe6K\xd4\\\xbf\xcb\x0c\x0c\xfc\x89\x94Z\x0e%<\x0ci\x1aU\xa9\x816\xb7\x84b\x9c,_]\x84\xd9x\x8c\x8b\xe0\xc7\xc5y?\xb7J.\x87\'\xb2\x1c|f9\x98\xcc\x12E\x8f\x84\xf8O\x1f\x7f\xf8\x9bSs\xa0\x9e\x8b\x0e\x94\xdc\xbe\xca\x8c\x8dj|9\x08\x9a\xb8\xf4c\x17\x8fu\x07\x1a\xdd\x92\x8ce\xb4\x92\xf1\x8b\xb0;\xa8\xe8(?\x9d\x8e\xe1\xf8U\x8d\xab\x9b\x85\xc7\x93d\x0e>\xca\x1cL\x94\x89"\x81\xda\xa0\xfe@1\x14 \xfce\x94y\xb2\x02#C\xb2\xccp\xfd\x8fX-\x1b\x1e\xcc\\R\xb06\xde\x8b\xb0;\xa4cdL~d\x9c\xf5r\xb3\xb0x\x02\xcd\xc1\'\x9a\x83I4QtO\x9aw\xc8\xe6m)d\xc0\xdbR\xaa\x89&*\xa02\x19J\xbc8-C\xee\xa6#\xd1\xe4\xbf\xfc\x96l\xf4\x83U\xc0]\x84]U\xa5\xcao=\x86F\x8d\xa7\x1b\x15(O\x9c9\xf8<\xd3L\xadV\x14\xdd\x7f\xf2\x9d\xb91\xebF\x03\x0c\xbbQ\xc2`\x13%\x14\x1c\x02m\xceS\xec&U\xa2\xb8ps\x8e&\xc1\x18\\\xba)\xbfU\xaf\x1c5\xben\x14\x1eO\xc69\xf8\x90s0!\'\x8a\xca\xe4\x19\x8bW\x12s\xf1Z\xcb8Q\xc0{\x8a@\x8eqL]\\\x8e\x91\xe1a\xce\xb8D{O\x11v\x8f\x81!9\xa7Z7\xcez\xb9\xd9\x96\xf2\xc4\x9c\x83\xcf9\x07\x93s\xa2\xe8Ql\xff\xe9\x97O?]\x7f\xdb\x9f\xffJ\xd5+\x1a\x00\xc5\x97\xa8\xd8\xbf\xca\x0c\x0e\x92pp\x08B9\xe7\xa0O\xc9\xd0\xe8\xb6\xa7\xc4\xd9\xdeS\x84\xdd\xe39\x99\xf8t\xd2\x85J\x8d\xb3\x9bE\xc8\x93\x82\x0e>\x065w\xd1\x15E\x7f\xfe\xe5\xfb\xef\xaf\xab\xdb}+\xc4\xa5\xa3\x1a\x84\xa2\x82\x13\x0ed\xa7\x18\x1e\x02M\x86a\xe9F\xc57<\x1c\x9a\xe6`eh\x17aw\x08\xc7\xf0\xc8\xbc\xb2|U\xe1\xe7V\xa1\x11\x9eL4\xf8Lt0\x99(\x8a\xfe\xf0\xdd\xd7?\xff\xfc\xf1\x9b\x97\x8b\x07\x1a\xc0\xc5\x03\x15\xbcx\xa0\x04\x1b\xb2J>\x19\xa6y\xec\xfacp\xf0_~+cc0\xe1\x97\xb0\xab:q\x82\xa4\xa2\xc7\x94\xa3\xca\xd7\x8d\x00Xxb\xd1\xe0cQ\xb3:[Qt/\xb0\xb6\xca\x1b\xaaX\xd4B\x15\x8b\xff<\xe1\r\x14@"\x1aJ89\xc5a\xec\xe6#\xdc@\x93[\t\x1b\x82y\x82"\xec\x1e\xd9\x86\xfc\xd2cH\x9cto\x9b\x044<ih\xf0ih\xb0\x1b7I\xf4O?~\xfb\xe1\xd3\x0f/2PT\xe36\x82\n\xca@Q\x80\xeb\x84\xe8\xdc\x0c!t\xc7\x1354\xb9\xb7]\xccf\xfe\x19\xdc\xd6M\xe7\xc3\xaf\xce\xbb\xb8\xd5\x02\xf1\xc4\xa0\xc1\xc7\xa0\xc1\xc4\xa0(z,j7t\xfb\xe5\xa7\x0f?[\xfe\xff\x03\xaaI\xf1%*\x00\x8f\xe3?\x8f\x89E\x10\x084\x8cK\x97\xf21(<\x04:M6\x1f\x17v\xd5A\xab\xfcV\xd5\x8ds\xde\xcd\xcd2\x8b\'\x00\r>\x005\x17\xc5\x15E\xf7H\xbe\x17\xd8\x1c\x1a\xa4\xe7\xd0 \x85\xd3\xe8]\x8dA\x83\x00\x92K\x98\xbb\xac\xf6\x10\x0f\x83\x8e\xe3bg\x16^Sg\xf0)h\x8d\xab\x9b\x85\xc7\x13\x84\x06\x1f\x84\x9ai\xf6\x8a\xa2{\x1b\xc9\xfa\xdd/^\xab/\xca\xf9\xf4\x04%\xb7\xaf2\x83\xa3\xba\xaf3\x94@2,!vA\xed\'\x1e\x06\x9d\'\xf3p\xfa"\xed\x1eI\x97\xf8\xd4\x88\x8e\xf3\x9en\x16\x1cO\x10\x1a|\x10j\xa6\xd9+\x8a\xee?\xf9\xb6\xd89\xb1Aj\'6HB\xbb\nvGbh\x08X\x19\xaf\x15\xc9\xacv\x15\x0f\x82\x86>\x99\xe5\xaa\xb4{\x8c\x0c\xc9@\x8f\xdd\xe0\xe7\xdd\xdc,0\x9e\x084\xf8\x084\x98\x08\x14E\x0f\xfc\xb2\x1d\x14c\xad\x8aj\xacUIAqQ\x8d@\x83\xa0\x91)N\xfaX\r\x8d\xee\xfb\xc9h^\x19\x11vu\xa5Z~\xaa\x8a\x92\xd3Nn\x16\x16O\x04\x1a|\x04\x1aL\x04\x8a\xa22;\xfa\x9f\xbf|\xfa\xfc\xd1\x0c\x0bR\x93\xe2KTPX\xe07P]"{>s\xdf\xcdj#\xf1\xd8\xe7<f;*\x92\xb7Z\x88\xaeO\x9d\x82\x9evr\xab\xd2\xe4\x89=\x83\x8f=\x83\x89=Q\xf4\x88\xe3\xad\x98\xe2\xd34\xd4\xf3i\x1aJ\xb0b%\x01FF\t c\x9e\x8f\xff\x9a\xde\xd0\xe2\xc6\xc4\'\xf3\x02\xdeEXUM]\xe2\xd3\xf1X"\x7fU\xe3\xe7V\xd7\r\x9f\xd8s\xf4\xb1\xa7y\xb5rE\xd1~\xc8\xf3\xa2\x11\x14\xd5H2P\x81\x8d\xa0\xa8\xe0\x9b\x87\x82y\xce\xcb\xd2\x1d\xfbl\xde\xd0\xe8\xb6fD\xfb\x0e\x89\xb0;\x1c\xc2\xed\x8fc\xef\xc6\xc6yG\xb7\xdaK\xc6\'\xf1\x1c}\xe29\x9a\xc4\x13E\xe5]\xa8{E\xc59(Z\xe1\x1c\x14%\\\xbe\xa2\x84\x83D\xf4g\xc6y\xea\xc2\xf1P\r\x8dnA2d\xf3,^\xd8\xd5AR~:\x1fC\xa4\xda\xe1\xcdB\xe5\xc9CG\x9f\x87\x8e&\x0fE\x918\xefq\x82\x84\xf4N\x90\x90\x04O\xd6P\xc11"\xa0\xe8\x9c\x96n<\x9e\xca\xa3\xd1\xbd_\xc3\x06`\xc2\xae\xaab\xc5\xa7*F*<\xdd,:\x8a;\xed>\x19\x1d\xedK\xed\xd8\xad\xb9/}>\xe0@\xb5\x13\x1b$!\xc0\x81\x02J>F\xd9\xc5\xb9\x8c\xddr\xec\xe4A\x9b{\xfaaO:\x10v\x8f\xd9\x87\xf8\xf0X\xab\x9cwr\xab\xcc\xe3\x89EG\x1f\x8b\x8e&\x16E\xd1{[\xda\xf5\x17#\x14E5BQT`PT#\xd1\xb1\xa4\x93a\x88\xa9[\x8eI)\xff\xd5[C\xb9\xdd\xc5#\xec\xaa\x93\xf8Q2\xd1t\x0c\x8c\xd3~n\xb6^<\x89\xe8\xe8\x13\xd1\xd1$\xa2(\x12k\x1c\x87\x06\xc994\xaa\xdbBQ\x01\x07\xae\xa3l\xdf\xd4\xdb\x88\x07C\xa7\xb4\xd8\x8b\x85\xdb\x13:\xca\x8b\xee\xc7\xf3\xb5\n\'\xb79s\x1d\x9f(t\xf4Q\xe8h\xa2P\x14\xbd\xff\xe0k\x1c;\xfd\xc2\xac\xe7~a\xd4\xe0\x9aQ\x8dCG\x81-\xf3\x90\xbb\xa8v\x12\x0f\x87\xc60\xdb\xc5JiW\xe7\xa1\x92\x87\x1e\tG\x8d\xaf\x9b\xad\x1aO":\xfaD\xd4\xe4|+\x8aD\x9b3\xb2/\x94#\xfbB\x05\xaf\x1a\xd5Pt\x14Pt\x9az\xdd\x17\xca\x7f\xf7\xad\xb7kY\xcc[(\xc2\xee\xf1\xaa\x81\xfcR\xbd\xa1\x9cwt\xb3\xd8xb\xd1\xd1\xc7\xa2\xe6\xa5\x9b\x15E\xf7x~\xcc\x81rV\x0f\xb4\xe0\xac\x1e\xa4q\xea\xd8\xca\x1b\xf1cI*\xd3\xed\x98M\x15\xb1~g\xa8\xb9\xd6^F\xd9qz\x8c\x0f\xd9\x19\xaa\x06-U9\xbb\xd1\xe6\xf2$\xa4\xa3OHG\x93\x90\xa2\xa8\x18\xeap\xfd\x8dx\xa0\x82z<PA\xc5\xf6MflTw\x86\x8e\xa234\x0f\xe1\xf8\xdf\xf2\x1b\xda\xdc\xba\xbc&\xbb1T\x98U\xd9\xa8\xf8Nu\x06[\xe3\xe8f\xa3\xb8\x9e\x8ct\xf2\x19\xe9h2R\x14=\xb0\xee}Z\xd4\x87\xaf\x7f0\x13R\xd4\x93\xe2KT\xf08.R\xd0<.y\xab=O\xddtd\xa4hr;\x85\x9d\xed\x03\xfa\xc9\xed\x0b\x15\x9f\x1aC\xb9*\x1c\xddf\xdd\x98\x9e\x8ct\xf2\x19\xe9d2R\x14=\x8e\x82v\xae\xcb\xa1\x81t\x14C\x83\x14\x08\xd0QApc\x12\x08s\x1e\x97\xeex\x10\xf2\xc6\x7f\xf7v\xf5\xd5\x1cwy\x11v\x8fI\x87\xf8\xd0\x08\x8d\nG7\x02\x1c\xd3\x13\x8aN>\x145)\xdf\x8a"\x19\xcd|\xec\x86\x06\xf8\xd8\r%\xbcp`\x9f%,\x1cb\xe0f\x9e\xc6\xae?2\x0e4\xb9e\xa4S\xb6\x83\xa3\xb4{,W&\xff\xd2|\x95\xa7\x1b-\x1cO&:\xf9Lt2\x99(\x8a\x1e\xf1\xbc\xf7\xb7R\xbe\x81r\xcc7PA\x07\xb2(\xc0eC\xe0\xc9\x14R7\x1f\x93Q\xfe\xabo\x95\xec\x90\xcc\xa3zaW\xdd\x8b\x96\xdf\xaa\x8a\x95\n?\xb7Z6\x8a\xc9\x9f>\x17\x9d\xec\xd1\x9f\xc8\xeb\xca_\x0c7\rP\x0c7\r\xf0\x9f\xc7\xa8\xa8\x86\xa2\x93\xc0\x93c\n\xc6n\xe2A\xd1a\xc9f\x8d"\xec\x1e\xb3\xd0\xc9\xef\x13=\xed\xe3f)\xe8\x13\x89N>\x12\x9dL$\x8a"q\xbd\x1f\xcf\xe9Q\x8e\xe7\xf4\xfc\x85\xb8\x91T"\xd1I4k\xe68t\xe1\xd8\xef\x85&7*\xbaD{&\xac\xa0\xa2*\x03\xf5n\xcaWx\xb9\xd1.\xf2d\xa2\x93\xcfD\'\x93\x89\xa2h?\xf4y\\\xa3\xa2iM(\xc7iM\xfc\x85xe\r%\xbcb\x088\x99\xc3\xa4G\xaf\xa0\xd1-2\x06\xbbCT\xd8U\xa3W&\xbfE\xb4\xc2\xd5\xcd\x16\x8d\'\x11\x9d|":\x99D\x14E\'\x87\x81\xa2\xde\x19#]{U\x1e\x05\xb4j\x88n\xce[\x97\xe8\xf1\xe2\xf2\x1b\x9a\xdcj\x93\xc9\x1e\xa1 \xed\xaa\xedD\x12\xd1coO\x8d\xa3\x1b-\x1cO :\xf9@t2\x81(\x8a\xee\x17%^\\\x84F9\xef\'\xa4@X\x8e\n^7DOg\xea{}#\x05\x8d\xee\x9d\xe5\x8b\xbdn\x08\x1az<\x95\x9f\x92\x1f\x1b\xe7=\xddl\xddx\xc2\xd0\xc9\x87\xa1\x93\tCQt\xff\xc9\xdeUW\xd4R\x02J\xff<]u\xe5\x1f\x07A!x\xe42L\xdd\xa8\x82\xc2\x83\xa0\xe3lOk\x12v\xf5f")\xa8J4Nz\xb8\xd1\xe8\xf9\'\xff\x9c}\xfe9\x99\xfc\x13E\xefC,_\x1c\xbd\xb2\x01><A\r\x1d\xbd\xa2\x00\x02c\x16\xa42\x84\xdc\xe5#\xc8@\x93\xdbj1\x9a\xf7@/\xd2\xee\xf1\x02\xdb,\xbbD\x8fYF\x95\xab\x1bE\xc7\x13\x81\xce>\x025\xaf\xf8\xae(\xba\xc7\xf2\x8b\xd2\x04\xe5\xb8\x95\xa0\x02K\x13\xfe\x89\x10\x1a\xa27t\n\xa1\x0b\xc7\x92\x15M\xee\xbd\xa1\xd1\xdcH\x84]\xf5.\x81w=\xbe\xc2\xc9\x8d\xa2\xe2\t?g\x1f~\xce&\xfcD\xd1\xa3\x1dm\xdb\xf5\x08o\xa1\x1a\xf1\x16*\xf8\xad\x8a\xeav\xd0Y\xb6m\x0e\xa3\xce=\xd1\xe8\x1e\x16\x8b9\x87G\xda=\x86\x85|\xe0\xe8\x88>\xcf\xfb\xb9Uv1?\xc9\xe7\xec\x93Os\xf2\xfe\x8a\xa2r\xd2\x03\x96\xac\xa8\xc6\x92\x15\x15\x94a\xa0\x80\xc0\xe7,\x10d\x9f\x83>KC\x9b[\xbd\x1a\xec&\x8d\xd9k\x06\x95_\xaa\x0e\xe1\xcf{\xb9\x11\xf6\x9c\x9f\xd8s\xf6\xb1\xe7lbO\x14\xdd\x7f\xf0~\xbe\x03Y\'\x8a!\xeb\xc4\x7f\x1e\x0f\xd1PA[H\t \xc71]\xeb\xd4\xe3Khh\xf2>;\xc1^+\x04\xf5<\xf6\xfc\xc9o\xd5\x8f\xdb\x9c\xf5q\xa3=\xa4x\xf3\xc8\x87\x9e\xb3\xfd\xe8\xd1\x8b\xfb\xda{\xab\x00\xf6\x81\xa2\x1c\xfb@Q\x81=\x19\xa8\xa0\xb0\x10\xf8\xb1Oc\xd7\x1f\xab\x114\xb9W#\xd9\xacF\x84]\x95s\xcaNP\x95s\x9ews\xa3\xb8xR\xcf\xd9\xa7\x9efk\xe3\x8a\xa2\xf2\xe1\r\x0e\x0bRsX\x90\x82\xa0\x16\n(*$\xf0\x9cc7\xab\xc4\xc2\x03\x9ei1o\x03_f\xb7\x07T|j\x84\xc5i/7\x8a\x8a\'\xed\x9c}\xda9\x9b\xb4\x13Er\xcc-\xd6!\xd5cAQ\xc1)\'\xf6\x98Rf!\x1e?\x9a\x96\xb1Kj\xb9\xf0h\xe7\xb4\xd8\xb7\\\x85\xdd\xe3\x11\x89\xf8P\xe5\x9b\xe7\xbd\xdc*\xb1x\xa2\xce\xd9G\x9d\xb3\x89:QTfB\x0c\xc1Q\xce\x10\x1c%\x98qVv}\xce\xa2\x01s\xc9\x83z\xb7\x00-n\xd7L`z\x9b0;L\xc7\xb0\x10_z\x0c\x8b\xf3Nn\xb4Z<\x19\xe7\xec3Ns\xf6\xe9\x8a\xa2\xc3\x08B\xdeF\xc8\x00o#\x88:\xf1\xec\x0c%\x14\x18%vL\xd7\xa4\xb3W\x81\xe1N\x02\x8dP\x88\x08\xd6y\xec\xc0\x98\xe5\xa5x\x15\x1a5\x9en\x13\x1c\xcb\x13x.>\xf04_\x04[QT\x8c\x83\xa1\xc7\x14IJ\xaf)\xd2?\x0f\x034\xf0\x9f\xa7\xc7\x14K\xde8\xc7\xa1\x9b\x8e\x1b\x08Z\xdc{r\xcc\x01\x88\x17aV]=\x12\x9f\x1e\xe3\xe1\xa4s\x1bE\xc2\x13n.>\xdc\\L\xb8\x89\xa2;w\xbb\xfdXn\xe0C57\xf0\xa1\x84\xe2\xa1\x12m.\x02A\xc6\xa0\xee\xfe\xbc\xa1\xc5}\x9c\x8a\xd9\xb4t9\x98=\xc6\x83|\x0b\xe9\xd8\xa3u\xde\xc9\x8d\x82\xe2\xc96\x17\x9fm.&\xdbD\x91(\xa31\xd3D9f\x9a\xa8@\\\x81\n\xca4\x17q\xe9<\xf7z\xd4#\x9a\xdcv\x8el\xd7\xa5\xc2\xac^\'$\xdb<viU\xf8\xb9Q\xae\xb9<\xd9\xe6\xe2\xb3\xcd\xc5d\x9b(\xba\xafm;\xa6\xc7\x9c\x02\xe5\x98S\xa0\x02\xcfBXA\xd8{\x11\xfd\x97\xd3\xd8\xebv\x1c4\xbaco{\xfc\xbc\xb0{,N\x17\x1foV8\xba\xd9\x0b\xcdO\xc0\xb9\xf8\x80s1\x01\'\x8a\xee\x95\xd3=\r\xc2\x0b\x8a\xa8\xc7\x0b\x8a\xa8\xe0\x84\x13%\xb4\x9dH\x1cy\xdbN\x8e\xf7\x13\xf9\xef\xdeo\xbc\xdb\xb1!@\xe616$\xe5T\xcbF\x85\xa3\x1bm(O\xd0\xb9\xf8\xa0\xd3l0YQTl\x80\xbchTcNTP\x8eQ\t9\x17\xd9\xd99\x8d\xfa\xd2*\x9a\xdc\x87c\xd8\x93a\x85\xdd\xe3\xf1\xe9"!\xa7\xca:\xcf\xba\xb8QD\x14\xef\xb9\xfb\x88\xd3\xfcSW\x14\x15o\xafP\x05R\xfb\x9e{-\xddD\x01\xef %i\xbc]\x0cP\x0fT\xa0\xcd\xed\x1e\xe2\x90L\x8a%\xcc*^\xb1H\xbcy\xec\xcb:\xe9\xe1f\xbb\xc7\x93n.>\xdd\\L\xba\x89\xa2\xf7\x97\xff\xf6U\x8dA\x16Z`\x90\x85\x12g\x03\xa9\xec\xe7\\\x04\xe1\x1c\xfa\xd4-\xc7\xb3S4\xb9\x13N\xb3\xc1\xf1"\xec\xaa.\x1c\xf1\xa9\x1e\x7fP\xe7\xecF+\xc6\x13s.>\xe64\x19\xcd\x8a\xa2\xe2\xe1P\xa7Ru\xda3\xa9R\xad\x1c\xfd\x89\xff<\x96$\xa2\xb12\x0e\xb9\x0b\xc7#T\xb4\xb9\x9d\x95M\xbd\xbd\x8d$74\x92\xbf\x8f\x9cvs\xab\x92\xe4\t:\x17\x1ft\x9a\xcd

In [20]:
import pandas as pd

df = pd.read_excel("HM_Fashion_Dataset_2000.xlsx")

df.head()

,article_id,product_name,product_type,color,section,price,customer_id,purchase_count,rating,description
0,ART00001,Formal Yellow Skirt,Skirt,Yellow,Kids,1425.02,CUST8329,3,4.4,Formal Yellow Skirt for Kids suitable for casu...
1,ART00002,Winter Grey Top,Top,Grey,Women,554.41,CUST8506,15,3.2,Winter Grey Top for Women suitable for casual ...
2,ART00003,Winter White Jacket,Jacket,White,Men,4513.98,CUST7583,6,4.6,Winter White Jacket for Men suitable for casua...
3,ART00004,Traditional Black Blazer,Blazer,Black,Women,1601.34,CUST3183,11,3.4,Traditional Black Blazer for Women suitable fo...
4,ART00005,Winter Yellow Top,Top,Yellow,Men,4270.10,CUST3275,20,3.9,Winter Yellow Top for Men suitable for casual ...

In [21]:
!pip install sentence-transformers faiss-cpu rank-bm25

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.2.2)
Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (1.13.2)
Requirement already satisfied: rank-bm25 in /usr/local/lib/python3.12/dist-packages (0.2.2)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.4.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.9.0+cpu)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.20.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.21.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)

In [22]:
import numpy as np
import faiss
from sentence_transformers import SentenceTransformer
from rank_bm25 import BM25Okapi

In [25]:
df.columns

Index(['article_id', 'product_name', 'product_type', 'color', 'section',
       'price', 'customer_id', 'purchase_count', 'rating', 'description'],
      dtype='object')

In [26]:
df["search_text"] = (
    df["product_name"].astype(str) + " " +
    df["product_type"].astype(str) + " " +
    df["color"].astype(str) + " " +
    df["section"].astype(str)
)

df.head()

,article_id,product_name,product_type,color,section,price,customer_id,purchase_count,rating,description,search_text
0,ART00001,Formal Yellow Skirt,Skirt,Yellow,Kids,1425.02,CUST8329,3,4.4,Formal Yellow Skirt for Kids suitable for casu...,Formal Yellow Skirt Skirt Yellow Kids
1,ART00002,Winter Grey Top,Top,Grey,Women,554.41,CUST8506,15,3.2,Winter Grey Top for Women suitable for casual ...,Winter Grey Top Top Grey Women
2,ART00003,Winter White Jacket,Jacket,White,Men,4513.98,CUST7583,6,4.6,Winter White Jacket for Men suitable for casua...,Winter White Jacket Jacket White Men
3,ART00004,Traditional Black Blazer,Blazer,Black,Women,1601.34,CUST3183,11,3.4,Traditional Black Blazer for Women suitable fo...,Traditional Black Blazer Blazer Black Women
4,ART00005,Winter Yellow Top,Top,Yellow,Men,4270.10,CUST3275,20,3.9,Winter Yellow Top for Men suitable for casual ...,Winter Yellow Top Top Yellow Men

In [23]:
model = SentenceTransformer("all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [27]:
embeddings = model.encode(df["search_text"].tolist(), show_progress_bar=True)

dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(np.array(embeddings))

Batches:   0%|          | 0/63 [00:00<?, ?it/s]

In [28]:
tokenized_corpus = [doc.split() for doc in df["search_text"]]
bm25 = BM25Okapi(tokenized_corpus)

In [29]:
def hybrid_search(query, top_k=5, alpha=0.6):

    # Semantic Search
    query_embedding = model.encode([query])
    distances, indices = index.search(np.array(query_embedding), top_k)
    semantic_scores = 1 / (1 + distances[0])

    # BM25
    tokenized_query = query.split()
    bm25_scores = bm25.get_scores(tokenized_query)
    bm25_scores = bm25_scores / np.max(bm25_scores)

    # Combine
    results = []
    for idx_pos, idx in enumerate(indices[0]):
        score = alpha * semantic_scores[idx_pos] + (1-alpha) * bm25_scores[idx]
        results.append((idx, score))

    results = sorted(results, key=lambda x: x[1], reverse=True)

    return df.iloc[[r[0] for r in results]]

In [30]:
hybrid_search("red party dress for women")

/tmp/ipython-input-1543476962.py:11: RuntimeWarning: invalid value encountered in divide
  bm25_scores = bm25_scores / np.max(bm25_scores)

,article_id,product_name,product_type,color,section,price,customer_id,purchase_count,rating,description,search_text
990,ART00991,Party Red Dress,Dress,Red,Women,2111.07,CUST3865,11,3.2,Party Red Dress for Women suitable for casual ...,Party Red Dress Dress Red Women
21,ART00022,Classic Red Dress,Dress,Red,Women,3236.89,CUST4441,16,3.9,Classic Red Dress for Women suitable for casua...,Classic Red Dress Dress Red Women
1269,ART01270,Stylish Red Dress,Dress,Red,Women,1338.64,CUST6176,17,4.1,Stylish Red Dress for Women suitable for casua...,Stylish Red Dress Dress Red Women
259,ART00260,Party Red Sweater,Sweater,Red,Women,4233.49,CUST2493,2,3.2,Party Red Sweater for Women suitable for casua...,Party Red Sweater Sweater Red Women
717,ART00718,Party Red Sweater,Sweater,Red,Women,4578.24,CUST1197,3,4.7,Party Red Sweater for Women suitable for casua...,Party Red Sweater Sweater Red Women

In [52]:

user_profile = {
    "preferred_color": "Red",
    "preferred_section": "Women",
    "preferred_type": "Dress"
}

In [32]:
def personalize_results(results, user_profile):

    personalized = results.copy()
    personalized["personal_score"] = 0

    for index, row in personalized.iterrows():

        score = 0

        if user_profile["preferred_color"].lower() in row["color"].lower():
            score += 1

        if user_profile["preferred_section"].lower() in row["section"].lower():
            score += 1

        if user_profile["preferred_type"].lower() in row["product_type"].lower():
            score += 1

        personalized.at[index, "personal_score"] = score

    personalized = personalized.sort_values(by="personal_score", ascending=False)

    return personalized

In [33]:
results = hybrid_search("party dress")
personalized_results = personalize_results(results, user_profile)

personalized_results[["product_name","color","section","personal_score"]]

/tmp/ipython-input-1543476962.py:11: RuntimeWarning: invalid value encountered in divide
  bm25_scores = bm25_scores / np.max(bm25_scores)

            product_name   color section  personal_score
143     Party Pink Dress    Pink    Kids               1
532     Party Pink Dress    Pink    Kids               1
1075    Party Pink Dress    Pink    Kids               1
1737    Party Pink Dress    Pink     Men               1
1447  Party Yellow Dress  Yellow    Kids               1

In [34]:
df["popularity_score"] = df["purchase_count"] * df["rating"]

In [35]:
def recommend_top_products(n=5):
    top_products = df.sort_values(by="popularity_score", ascending=False).head(n)
    return top_products

In [36]:
recommend_top_products(5)[["product_name","popularity_score"]]

             product_name  popularity_score
364    Summer Green Skirt             100.0
30    Summer Black Jacket             100.0
513     Party Beige Kurti             100.0
1000    Summer Blue Jeans              98.0
159   Stylish Beige Saree              98.0

In [49]:
!pip install streamlit

Requirement already satisfied: streamlit in /usr/local/lib/python3.12/dist-packages (1.54.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.9.1)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.3)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.16.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.1.4)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)

In [53]:
import random

reviews = [
    "Amazing quality and very comfortable",
    "Poor stitching and bad material",
    "Perfect for party wear, loved it",
    "Not worth the price",
    "Very stylish and elegant design",
    "Color faded after one wash"
]

df["review_text"] = [random.choice(reviews) for _ in range(len(df))]

In [54]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.3)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.4.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers) (8.3.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)

In [55]:
from transformers import pipeline

sentiment_model = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

In [56]:
df["sentiment"] = df["review_text"].apply(lambda x: sentiment_model(x)[0]["label"])
df[["product_name","review_text","sentiment"]].head()

               product_name                           review_text sentiment
0       Formal Yellow Skirt       Very stylish and elegant design  POSITIVE
1           Winter Grey Top       Very stylish and elegant design  POSITIVE
2       Winter White Jacket            Color faded after one wash  NEGATIVE
3  Traditional Black Blazer  Amazing quality and very comfortable  POSITIVE
4         Winter Yellow Top      Perfect for party wear, loved it  POSITIVE

In [57]:
df["is_fake"] = df["review_text"].apply(lambda x: 1 if "price" in x.lower() else 0)

In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["review_text"])
y = df["is_fake"]

model_fake = LogisticRegression()
model_fake.fit(X, y)

LogisticRegression()

In [59]:
sample_review = ["This product is amazing and premium quality"]
sample_vec = vectorizer.transform(sample_review)

model_fake.predict(sample_vec)

array([0])